# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_employee_account_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Recharge',
        ),
    ]
